/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BatchDeleteDialog: typeof import('./components/datagrid/BatchDeleteDialog.vue')['default']
    BatchUpdateDialog: typeof import('./components/datagrid/BatchUpdateDialog.vue')['default']
    BatchWriteDialog: typeof import('./components/datagrid/BatchWriteDialog.vue')['default']
    ConnectionItem: typeof import('./components/sidebar/ConnectionItem.vue')['default']
    DataGrid: typeof import('./components/datagrid/DataGrid.vue')['default']
    DataGridCell: typeof import('./components/datagrid/DataGridCell.vue')['default']
    DataGridFilterRow: typeof import('./components/datagrid/DataGridFilterRow.vue')['default']
    DataGridHeaderMenu: typeof import('./components/datagrid/DataGridHeaderMenu.vue')['default']
    DataGridStatusBar: typeof import('./components/datagrid/DataGridStatusBar.vue')['default']
    DataGridToolbar: typeof import('./components/datagrid/DataGridToolbar.vue')['default']
    DataResultTable: typeof import('./components/DataResultTable.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTab: typeof import('naive-ui')['NTab']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NVirtualList: typeof import('naive-ui')['NVirtualList']
    PrimaryNav: typeof import('./components/layout/PrimaryNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/sidebar/Sidebar.vue')['default']
    StatusMessageBridge: typeof import('./components/StatusMessageBridge.vue')['default']
  }
}
